#!/usr/bin/env zsh
# This hook is run after a new virtualenv is activated.

#
#easy_install pip

#
pip install virtualenv virtualenvwrapper

#
# pip install distribute

# interactive shell
pip install ipython ptpython
# pip install bpython

# debug
pip install Werkzeug

pip install awscli

# easy_install -U distribute

# debug
pip install pudb ipdb
# pip install django-pudebug

# TEST
pip install mock tox pytest

# document
# pip install Sphinx

# deployed
# pip install South
# pip install Fabric

# peformance, analysis
pip install pyflakes pep8 pylint flake8 pydocstyle
pip install -U flake8 flake8-import-order autoflake autopep8 black isort
# pip install clonedigger

pip install pgcli mycli httpie

pip install awscli

#  ******************************************************************************
#  libedit detected - readline will not be well behaved, including but not limited to:
#    * crashes on tab completion
#    * incorrect history navigation
#    * corrupting long-lines
#    * failure to wrap or indent lines properly
#  It is highly recommended that you install readline, which is easy_installable:
#      easy_install readline
#  Note that `pip install readline` generally DOES NOT WORK, because
#  it installs to site-packages, which come *after* lib-dynload in sys.path,
#  where readline is located.  It must be `easy_install readline`, or to a custom
#  location on your PYTHONPATH (even --user comes after lib-dyload).
#  ******************************************************************************

# ipython readline
pip install readline

pip install pip -U

echo <<_EOF_

more packages, install to ::

    $ ~/.virtualenvs/django-packages
    $ ~/.virtualenvs/tornado-packages
    $ ~/.virtualenvs/flask-packages

_EOF_

