#!/usr/bin/env zsh
# This hook is run after a new virtualenv is activated.

#
#easy_install pip

#
pip install virtualenv virtualenvwrapper

#
pip install distribute

# ipython
pip install ipython

# django
pip install django

# debug
pip install Werkzeug

# debug
pip install pudb debug ipdb django-pudebug

# TEST
pip install nose nose-pudb django-nose

# CI
pip install django-jenkins

# image library
pip install PIL

# document
pip install Sphinx

# deployed
pip install South Fabric

# django extra
pip install django-debug-toolbar
pip install django-extensions

# datastorage
pip install MySQL-python
pip install pysqlite

# peformance, analysis
pip install pyflakes pep8 reimport pylint clonedigger


#  ******************************************************************************
#  libedit detected - readline will not be well behaved, including but not limited to:
#    * crashes on tab completion
#    * incorrect history navigation
#    * corrupting long-lines
#    * failure to wrap or indent lines properly
#  It is highly recommended that you install readline, which is easy_installable:
#      easy_install readline
#  Note that `pip install readline` generally DOES NOT WORK, because
#  it installs to site-packages, which come *after* lib-dynload in sys.path,
#  where readline is located.  It must be `easy_install readline`, or to a custom
#  location on your PYTHONPATH (even --user comes after lib-dyload).
#  ******************************************************************************

# ipython readline
easy_install readline



