#!/usr/bin/env zsh
# This hook is run after every virtualenv is activated.

# set paths
export VIRTUAL_ENV_PYTHON_LIB=$VIRTUAL_ENV/lib
export PYTHON_LIB=$PYTHON_HOME/lib

# ganegate rc file
gen_virtualenvwrapper_postzshrc
