#!/usr/bin/env zsh

mkdir /tmp/startup
cd /tmp/startup

if [ $DISTRIBUTE = ubuntu ]; then
  sudo aptitude install python2.7 python2.7-dev -y
  sudo aptitude install curl build-essential mysql-server sqlite3 -y
  sudo aptitude install libsqlite3-dev libmysqlclient-dev libpng-dev -y

  curl -O http://peak.telecommunity.com/dist/ez_setup.py
  sudo python2.7 ez_setup.py

  sudo easy_install-2.7 virtualenv
  sudo easy_install-2.7 virtualenvwrapper

  virtualenvwrapper.sh
  echo ''
  echo ''
  echo "mkvirtualenv --python=/usr/bin/python2.7 --distribute first_project"
  mkvirtualenv --python=/usr/bin/python2.7 --distribute first_project
fi

rm -rf /tmp/startup
