#!/bin/sh

mkdir ~/git
cd ~/git
git clone git://github.com/splhack/macvim.git
cd macvim
./configure -prefix=$HOME -enable-pythoninterp --with-features=huge --enable-cscope --enable-multibyte
make
make install

echo "example:: next command"
echo
echo "git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle"
echo
echo "vim -c 'BundleInstall'"
echo
echo "cd ~/.vim/bundle/vimproc/ && make -f make_gcc.mak"
echo
echo "Note: please installed python hashlib module."

