#!/usr/bin/env zsh


# alias
if [ $ARCHI = darwin ]; then
  alias sudo='sudo '
  alias emacs='open -a /Applications/Emacs.app'
  alias vi='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
  alias vim='env LANG=ja_JP.UTF-8 nvim'
  # alias vim='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
  alias mvi='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/MacVim "$@"'
  alias mvim='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/MacVim "$@"'
  alias gvim='env LANG=ja_JP.UTF-8 open -a "/Applications/MacVim.app/Contents/MacOS/MacVim" "$@"'
  alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
  alias d="sudo docker"
  alias ls='gls -Fh --color=auto'
  alias updatedb=' sudo LC_ALL=C gupdatedb --prunepaths="/tmp /var/tmp /.Spotlight-V100 /.fseventsd /Volumes/MobileBackups /Volumes/Volume /.MobileBackups" '
  alias locate='glocate -i '
  alias winscp="open $HOME/Library/Application\ Support/MikuInstaller/prefix/default/drive_c/Program\ Files/WinSCP/WinSCP.exe"
  alias dircolors='gdircolors'
  alias gdb='ggdb'
  alias wholediff="diff --new-line-format='+%L' --old-line-format='-%L' --unchanged-line-format=' %L'"
  alias grep='ggrep -i --color=always '
  alias grepR='\ggrep -inHR --color=always -e '
  alias grepRspecify='\ggrep -nHR --color=always -e '
  alias grepRuncolor='\ggrep -inHR -e '
  alias grepRnocolor='\ggrep -inHR -e '
  alias d='sudo docker'
  alias less='less -MX'

  # alias eog='open -a Preview'
  # alias -s {png,jpg,bmp,PNG,JPG,BMP}=eog

  # Trim new lines and copy to clipboard
  # alias c="tr -d '\n' | pbcopy"
  # alias c=tmux-pbcopy
  # alias v='vagrant'
fi
if [ $ARCHI = freebsd ]; then
  alias ls='ls -FGh'
fi
if [ $ARCHI = linux ]; then
  alias ls='ls -Fh --color=auto'
  alias d="sudo docker"
  alias vim='env LANG=ja_JP.UTF-8 nvim'
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
  alias grep='grep -i --color=always '
  alias grepR='\grep -inHR --color=always -e '
  alias grepRspecify='\grep -nHR --color=always -e '
  alias grepRuncolor='\grep -inHR -e '
  alias grepRnocolor='\grep -inHR -e '
fi
if [ $ARCHI = cygwin ]; then
  ;
fi

alias b='rbenv exec bundle'

# general
alias top='htop'
alias py=python
alias rb=ruby
# if [[ -x `which rlwrap` ]]; then
  # alias coffee="rlwrap coffee"
# fi
alias screen='screen -U'
alias l='ls'
alias ll='ls -alt'
alias lll='ls && ls -alt'
alias llll='tree -ahsgupDF  -L 2 && lll'
alias lllll='tree -ahsgupDF  -L 3 && lll'
alias llllll='tree -ahsgupDF  -L 4 && lll'
alias lllllll='tree -ahsgupDF  -L 5 && lll'
alias llllllll='tree -ahsgupDF  -L 6 && lll'
alias lllllllll='tree -ahsgupDF  -L 7 && lll'
alias llllllllll='tree -ahsgupDF  -L 8 && lll'
alias lllllllllll='tree -ahsgupDF  -L 9 && lll'
alias llllllllllll='tree -ahsgupDF  -L 10 && lll'
alias lllllllllllll='tree -ahsgupDF  -L 11 && lll'
alias llllllllllllll='tree -ahsgupDF  -L 12 && lll'
alias lllllllllllllll='tree -ahsgupDF  -L 13 && lll'
alias llllllllllllllll='tree -ahsgupDF  -L 14 && lll'
alias lllllllllllllllll='tree -ahsgupDF  -L 15 && lll'
alias llllllllllllllllll='tree -ahsgupDF  -L 16 && lll'
alias lllllllllllllllllll='tree -ahsgupDF  -L 17 && lll'
alias la='ls -lt'
alias vi='vim'
alias clvim="setopt rm_star_silent; rm -rf ~/.vim_plugins/vim_session/*; unsetopt rm_star_silent; vim "
alias novim="vim -u NONE -U NONE --noplugin "
alias cp='cp -iv'
alias mv='mv -iv'
alias tmux='tmux -2 -u'
alias which='which'
alias cl='clear'
alias pb='tmux-pbcopy'
alias ec="extract"
alias b='rbenv exec bundle'
alias vimbundle-clean="vim +NeoBundleClean +qall"
alias vimbundle-update="vim +NeoBundleUpdate +qall"
alias vimbundle-install="vim +NeoBundleInstall +qall"

alias dstat-full='dstat -Tclmdrn'
alias dstat-mem='dstat -Tclm'
alias dstat-cpu='dstat -Tclr'
alias dstat-net='dstat -Tclnd'
alias dstat-disk='dstat -Tcldr'

alias dstat-all='sudo dstat -af'
alias dstat-top='sudo dstat -ta --top-cpu'
alias dstat-io='sudo dstat -ta --top-io-adv --top-bio-adv'

# ROT13-encode text. Works for decoding, too! ;)
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sed -e 's/inet6* //'"

# ssh
alias sshtor='\ssh -o "ProxyCommand nc -X 5 -x 127.0.0.1:9050 %h %p" '

# Enhanced WHOIS lookups
# alias whois="whois -h whois-servers.net"

# cd
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias ......="cd ../../../../../"
alias .......="cd ../../../../../../"
alias ........="cd ../../../../../../../"
alias .........="cd ../../../../../../../../"
function - { cd -; }
alias gd='source $HOME/.zsh_extend/gd/gd.sh'
alias cdh='gd'
alias cdd='gd'
alias cdhistory='gd'
# -g
alias -g L="| $PAGER"
alias -g G="| grep"
# alias -s
# alias -s py=python
# alias -s rb=ruby
# alias -s js=node
# alias -s coffee=coffee
# alias -s hs=runhaskell
# alias -s {png,jpg,bmp,PNG,JPG,BMP}=eog
# alias -s {gz,tgz,zip,rar,tbz2,lzh,bz2,tbz,Z,7z,lzma,tar,arj,xz}=extract

# rsync
# alias rsync_gigacast_dev='source $HOME/script/shell/rsync_gigacast_dev'
# alias rsync_gigacast_v14_dev='source $HOME/script/shell/rsync_gigacast_v14_dev'
# alias rsync_gigacast_plcdn='source $HOME/script/shell/rsync_gigacast_plcdn'
# alias rsync_gigacast_aidia='source $HOME/script/shell/rsync_gigacast_aidia'
# alias rsync_gigacast_gaitame='source $HOME/script/shell/rsync_gigacast_gaitame'
# alias rsync_gigacast_jikiden='source $HOME/script/shell/rsync_gigacast_jikiden'
# alias rsync_gigacast_local_dev='source $HOME/script/shell/rsync_gigacast_local_dev'

source ~/.kubectl_aliases

# python
alias mkvirtualenv="mkvirtualenv --no-site-packages --distribute "

# kube
alias kubestats="kubectl get node,po,deploy,sts,svc,job,ing,pv,pvc,configmap,secret,hpa,endpoints -o wide"
alias fzfkubernetesalias="fzf --height 25 --header-lines=1 --reverse --multi --cycle"
alias -g P='$(kubectl get pods | fzfkubernetesalias | awk "{print \$1}")'

# Like P, global aliases about kubernetes resources
alias -g  PO='$(kubectl get pods | fzfkubernetesalias | awk "{print \$1}")'
alias -g  NS='$(kubectl get ns   | fzfkubernetesalias | awk "{print \$1}")'
alias -g  RS='$(kubectl get rs   | fzfkubernetesalias | awk "{print \$1}")'
alias -g SVC='$(kubectl get svc  | fzfkubernetesalias | awk "{print \$1}")'
alias -g ING='$(kubectl get ing  | fzfkubernetesalias | awk "{print \$1}")'

