#!/usr/bin/env zsh

# alias
if [ $ARCHI = darwin ]; then
  alias emacs='open -a /Applications/Emacs.app'
  #alias emacs_sudo='sudo open -a /Applications/MacPorts/Emacs.app'
  alias vi='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
  alias vim='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
  alias mvi='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/MacVim "$@"'
  alias mvim='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/MacVim "$@"'
  # alias ls='ls -FGh'
  alias ls='gls -Fh --color=auto'
  alias updatedb=' sudo LC_ALL=C gupdatedb --prunepaths="/tmp /var/tmp /.Spotlight-V100 /.fseventsd /Volumes/MobileBackups /Volumes/Volume /.MobileBackups" '
  alias locate='glocate -i '
  alias winscp="open $HOME/Library/Application\ Support/MikuInstaller/prefix/default/drive_c/Program\ Files/WinSCP/WinSCP.exe"
  alias mysql='mysql5'
  alias dircolors='gdircolors'
fi
if [ $ARCHI = freebsd ]; then
  alias ls='ls -FGh'
fi
if [ $ARCHI = linux ]; then
  alias ls='ls -Fh --color=auto'
fi
if [ $ARCHI = cygwin ]; then
  ;
fi

# general
alias top='htop'
alias py=python
alias screen='screen -U'
alias la='ls -alt'
alias vi='vim'
alias clvim="setopt rm_star_silent; rm -rf ~/.vim_plugins/vim_session/*; unsetopt rm_star_silent; vim "
alias less='less -MX'
alias grep='grep -i --color=always '
alias cp='cp -iv'
alias mv='mv -iv'
alias tmux='tmux -2'
alias which='which -a'
alias cl='clear'
alias pb='tmux-pbcopy'
# cd
alias ...="../../"
function - { cd -; }
alias gd='source $HOME/.zsh_extend/gd/gd.sh'
alias cdh='gd'
alias cdd='gd'
alias cdhistory='gd'
# -g
alias -g L="| $PAGER"
alias -g G="| grep"

# rsync
alias rsync_gigacast_dev='source $HOME/script/shell/rsync_gigacast_dev'
alias rsync_gigacast_v14_dev='source $HOME/script/shell/rsync_gigacast_v14_dev'
alias rsync_gigacast_plcdn='source $HOME/script/shell/rsync_gigacast_plcdn'
alias rsync_gigacast_aidia='source $HOME/script/shell/rsync_gigacast_aidia'
alias rsync_gigacast_gaitame='source $HOME/script/shell/rsync_gigacast_gaitame'
alias rsync_gigacast_jikiden='source $HOME/script/shell/rsync_gigacast_jikiden'
alias rsync_gigacast_local_dev='source $HOME/script/shell/rsync_gigacast_local_dev'


# python
alias mkvirtualenv="mkvirtualenv --no-site-packages --distribute "


