#!/usr/bin/env zsh


setopt bang_hist                 # Treat the '!' character specially during expansion.
setopt extended_history          # Write the history file in the ":start:elapsed;command" format.
setopt inc_append_history        # Write to the history file immediately, not when the shell exits.
setopt share_history             # Share history between all sessions.
setopt hist_expire_dups_first    # Expire duplicate entries first when trimming history.
setopt hist_ignore_dups          # Don't record an entry that was just recorded again.
setopt hist_ignore_all_dups      # Delete old recorded entry if new entry is a duplicate.
setopt hist_find_no_dups         # Do not display a line previously found.
setopt hist_ignore_space         # Don't record an entry starting with a space.
setopt hist_save_no_dups         # Don't write duplicate entries in the history file.
setopt hist_reduce_blanks        # Remove superfluous blanks before recording entry.
setopt hist_verify               # Don't execute immediately upon history expansion.
setopt hist_beep                 # Beep when accessing nonexistent history.
setopt append_history            # If this is set, zsh sessions will append their history list to the history file
setopt complete_aliases          # Prevents aliases on the command line from being internally substituted before completion is attempted.
setopt hist_expand
setopt transient_rprompt
setopt prompt_subst
setopt nobeep
setopt nolistbeep
setopt long_list_jobs
setopt list_types
setopt auto_resume
setopt auto_list
setopt print_eight_bit
setopt histignorealldups histsavenodups
# setopt histignorespace
setopt auto_pushd
setopt autopushd
setopt pushd_ignore_dups
setopt mark_dirs
setopt auto_menu
setopt equals
setopt auto_menu
setopt magic_equal_subst
setopt auto_cd
setopt auto_param_keys
setopt auto_param_slash
setopt correct
setopt numeric_glob_sort
#setopt rm_star_silent
#setopt rm_star_wait
#setopt short_loops
#setopt single_line_zle
# setopt xtrace
setopt print_exit_value
#setopt correct_all

unsetopt promptcr



