#!/usr/bin/env zsh

# history
zshaddhistory() {
    local line=${1%%$'\n'}
    local cmd=${line%% *}

    # Adding executed command into history along the following rules.
    # Enumerate below, these are not wanted to add.
    #
    # * Less than 4 characters
    # * A pert of command is l, ls, la, ll
    # * A pert of command is c, cd
    # * A pert of command m, man

    [[ ${#line} -ge 5
        && ${cmd} != (l|l[sal])
        && ${cmd} != (c|cd)
        && ${cmd} != (sl)
# && ${cmd} != (gd)
        && ${cmd} != (m|man)
    ]]
}


# http://www.quark.kj.yamagata-u.ac.jp/~hiroki/zsh/zsh.cgi
# environment variable set into tmux
function chpwd(){
    [ $TMUX ] && tmux -2 setenv TMUXPWD_$(tmux -2 display -p "#I") $PWD
}

# sette
#function chpwd(){
# _reg_pwd_screennum
#}


# growl
# if [ $ARCHI = darwin ]; then
  # # growlnotify exevute  30 second later
  # local COMMAND=""
  # local COMMAND_TIME=""
  # precmd() {
    # if [ "$COMMAND_TIME" -ne "0" ] ; then
      # local d=`date +%s`
      # d=`expr $d - $COMMAND_TIME`
      # if [ "$d" -ge "30" ] ; then
         # COMMAND="$COMMAND "
         # growlnotify -t "${${(s: :)COMMAND}[1]}" -m "$COMMAND" 2> /dev/null
      # fi
    # fi
    # COMMAND="0"
    # COMMAND_TIME="0"

    # # prompt vcs_info
    # psvar=()
    # LANG=en_US.UTF-8 vcs_info
    # psvar[1]=$vcs_info_msg_0_
  # }

  # preexec () {
    # COMMAND="${1}"
    # COMMAND_TIME=`date +%s`
  # }
# fi

