# keypress_delay_ms: 20

modmap:
  - name: Global
    remap:
      # CapsLock/Ctrl_L -> Esc
      # CapsLock: Esc
      # Ctrl_L: Esc
      CapsLock: Ctrl_L

      # HHKB: [Alt_L] [Muhenkan] [Space] [Henkan] [KatakanaHiragana]
      # Alt_L: Ctrl_R # for Ctrl+Click
      # Muhenkan: Ctrl_L
      # Henkan: Shift_L

keymap:
  - name: Google Search
    application:
      only: Google-chrome
    remap:
      # Emacs basic
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      C-d: delete
      # Emacs word
      Super-d: C-delete
      Super-b: C-left
      Super-f: C-right
      # Emacs lines
      C-a: home # TODO: Alt-C-a
      C-e: end # TODO: Alt-C-e
      C-k: [Shift-end, backspace] # TODO: Alt-C-k
      C-h: backspace
      # Back Prev
      M-leftbrace: M-left
      M-rightbrace: M-right
      # Ctrl -> Alt
      M-left: C-left
      M-right: C-right
      M-Shift-left: C-Shift-left
      M-Shift-right: C-Shift-right
      M-Shift-t: C-Shift-t
      M-a: C-a
      M-c: C-c
      M-f: C-f
      M-g: C-g
      M-l: C-l
      M-n: C-n
      M-o: C-o
      M-p: C-p
      M-r: C-r
      M-s: C-s
      M-t: C-t
      M-v: C-v
      M-w: C-w
      M-x: C-x
      M-z: C-z

  - name: Terminal
    application:
      only: [gnome-terminal-server, Gnome-terminal, Alacritty]
    remap:
      Super-o: M-o
      Super-p: M-p
      Super-j: M-j
      Super-k: M-k
      Super-r: M-r
      Super-b: M-b
      Super-f: M-f
      Super-d: M-d
      Super-i: M-i
      Super-w: M-w
      Super-t: M-t
      Super-c: M-c
      Super-v: M-v
      # M-c: C-Shift-c
      # M-v: C-Shift-v
      # M-t: C-Shift-t
      # M-w: C-Shift-w
      # M-g: C-Shift-g
      # M-h: C-Shift-h
      # M-j: C-Shift-j
      #C-TAB: C-PAGE_DOWN
      #C-Shift-TAB: C-PAGE_UP
      # M-f: C-Shift-f

  - name: Nocturn
    application:
      only: Nocturn
    remap:
      Super-j: M-j
      Super-k: M-k
      Super-o: M-o
      Super-p: M-p
      Super-p: M-p
      Super-Enter: Shift-Enter

  - name: Slack
    application:
      only: Slack
    remap:
      Super-o: C-Shift-tab
      Super-p: C-tab
      Super-n: C-k
      Super-k: M-up
      Super-j: M-down
      C-M-k: Shift-Alt-up
      C-M-j: Shift-Alt-down

      Super-1: C-1
      Super-2: C-2
      Super-3: C-3
      Super-4: C-4
      Super-5: C-5
      Super-6: C-6
      Super-7: C-7
      Super-8: C-8
      Super-9: C-9

      # Emacs basic
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      C-d: delete
      # Emacs word
      Super-d: C-delete
      Super-b: C-left
      Super-f: C-right
      # Emacs lines
      C-a: home # TODO: Alt-C-a
      C-e: end # TODO: Alt-C-e
      C-k: [Shift-end, backspace] # TODO: Alt-C-k
      C-h: backspace
      # Back Prev
      M-leftbrace: M-left
      M-rightbrace: M-right
      # Ctrl -> Alt
      M-left: C-left
      M-right: C-right
      M-Shift-left: C-Shift-left
      M-Shift-right: C-Shift-right
      M-Shift-t: C-Shift-t
      M-a: C-a
      M-c: C-c
      M-f: C-f
      M-g: C-g
      M-l: C-l
      M-n: C-n
      M-o: C-o
      M-p: C-p
      M-r: C-r
      M-s: C-s
      M-t: C-t
      M-v: C-v
      M-w: C-w
      M-x: C-x
      M-z: C-z

#  - name: IDEA (modified from Default)
#    application:
#      only: jetbrains-idea
#    remap:
#      # Emacs basic
#      # C-b: left  # for Vim
#      # C-f: right # for Vim
#      C-p: up
#      C-n: down
#
#      # Emacs word
#      Super-b: C-left
#      Super-f: C-right
#
#      # Emacs lines
#      C-a: home # TODO: Alt-C-a
#      C-e: end # TODO: Alt-C-e
#      C-k: [Shift-end, backspace] # TODO: Alt-C-k
#
#      # Alt -> Ctrl
#      M-a: C-a
#      M-z: C-z
#      M-x: C-x
#      #M-c: C-c # use C-c for Esc, M-c for copy
#      #M-v: C-v # use C-v for Vim, M-v for paste
#      #M-w: C-w # avoid conflict with prefix
#      M-t: C-t
#      M-l: C-l
#
#      # actually these are vim insert mode bindings, but compatible with shell
#      # C-w: [C-Shift-left, delete]
#
#      C-d: delete
#      Super-d: C-delete
#
#      # workaround prefix key bug
#      M-r:
#        remap:
#          '3': C-M-3
#          '0': C-M-0
#
#      # workaround
#      C-c: Esc

  - name: Default -- some of these are overridden by the above definitions
    application:
      not: [Google-chrome, Slack, gnome-terminal-server, Gnome-terminal, jetbrains-idea, Alacritty]
    remap:
      # Emacs basic
      C-b: left
      C-f: right
      C-p: up
      C-n: down

      # Emacs word
      Super-b: C-left
      Super-f: C-right

      # Emacs lines
      C-a: home # TODO: Alt-C-a
      C-e: end # TODO: Alt-C-e
      C-k: [Shift-end, backspace] # TODO: Alt-C-k
      C-h: backspace

      # Super -> Ctrl
      Super-a: C-a
      Super-z: C-z
      Super-x: C-x
      Super-c: C-c
      Super-v: C-v
      Super-w: C-w
      Super-t: C-t
      Super-l: C-l

      # Tab changes + Alt-Enter simulation
      Super-o: C-Shift-tab
      Super-p: C-tab
      Super-Enter: M-Enter

      # actually these are vim insert mode bindings, but compatible with shell
      C-w: [C-Shift-left, delete]

      C-d: delete
      Super-d: C-delete

      # Underscore without Shift
      RO: Shift-RO

      # SKK hack for Chrome
      C-j: C-m

  - name: Default Global
    remap:
      M-Space: Super-Space
      C-Enter: Super-s

